[tool.poetry]
name = "fastapi-poetry-demo"
version = "0.1.0"
description = ""
authors = ["tx7do <yanglinbo@gmail.com>"]
readme = "README.md"
packages = [{ include = "fastapi_poetry_demo" }]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.100.0"
uvicorn = "^0.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
